.TH GSWITCH "1" "1.1" "Ferry Hendrikx"
.SH NAME
gswitch \- Program that randomly changes your GNOME2 background.
.SH "SYNTAX"
.LP
.B perl gswitch [-d] [-t <minutes>]
.SH DESCRIPTION
Gswitch automatically changes your GNOME desktop background every 't'
minutes (where t defaults to 20 and can be changed from the command
line). Background images and style settings are sourced from your list 
of backgrounds as configured in 'System > Preferences > Appearance'. By 
default, images are switched after 20 minutes. Although the images
are shown randomly, every image will be shown before you see any
repeats.
.LP
This program was written using Perl and GTK2.
.SH SEE ALSO
Homepage: http://gswitch.googlecode.com/
.SH AUTHOR
GSWITCH was developed by Ferry Hendrikx <ferry.hendrikx@gmail.com>.
.PP
This manual page was written by Ferry Hendrikx for the GSWITCH project, 
and may be used by anyone.
